# Site settings
title: DKScript
#email: tiff2766@gmail.com
description: >
  DKGL development blog.
  https://github.com/hongtae/DKGL
baseurl: ""
github_username: hongtae

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
permalink: /:year:month:day/:title/

# Markdown Processor Extensions

# Site variables
DKGLrepoUrl: https://github.com/Hongtae/DKGL/tree/develop/

